FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --target=/app/deps

FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /app/deps /app/deps
ENV PATH=/app/deps/bin:$PATH

COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
